---
title: "Sesi칩n 4"
subtitle: "Arreglos <br> Parte 2"
author: "Joselyn Ch치vez"
date: "05/03/2022"
output:
  xaringan::moon_reader:
    css: "perl.css"
    self_contained: true
    nature:
      ratio: '16:9'
---

# Accediendo a los elementos usando ciclos

```{Perl,eval=FALSE}
my @arreglo = (1,2,3,4,5);
my @suma = @arreglo + 1;
print "@arreglo\n@suma\n";
```

programa_01.pl

---

Este comando no funciona con arreglos, es necesario extraer cada elemento

```{Perl,eval=FALSE}
my $nElementos = @arreglo;
my @suma;
my $i;

for ($i = 0; $i <= $nElementos; $i++) {
	push(@suma,$arreglo[$i]+1);
}

print "La suma es: @suma\n";
```

programa_01.pl

---
# Otra forma, usando while

```{Perl,eval=FALSE}
my @arreglo = (1,2,3,4,5);
my @suma;
my $nPosicion = scalar(@arreglo);
my $i = 0;

while($i < $nPosicion) {
	push(@suma,$arreglo[$i]+1);
	$i++;
}

print "La suma es: @suma\n";
```

programa_02.pl

---
# Alternativa: usar foreach

```{Perl,eval=FALSE}
my @arreglo = (1,2,3,4,5);
my @suma;

foreach my $elemento (@arreglo) {
	push(@suma,$elemento +1);
}

print "La suma es: @suma\n";
```

programa_03.pl

---

## Ejercicio

Teniendo el arreglo:

```{Perl,eval=FALSE}
my @nombres = ("Andrea","Alberto","Lucia","Julio","Fernanda");
```

- Utiliza el acceso mediante ciclos al arreglo y agrega un apellido a cada nombre.

- Imprime el arreglo final que contiene a los nombres y apellidos.

programa_04.pl

---

# Generando combinaciones de arreglos

```{Perl,eval=FALSE}
my @arreglo1 = (1,2,3,4,5);
my @arreglo2 = ("A","B","C","D","E");

foreach my $elemento1 (@arreglo1) {
	foreach my $elemento2 (@arreglo2) {
		print "$elemento1$elemento2\n"; 
	}
}
```

programa_05.pl

---

## Ejercicio

Modifica tu programa de nombres y apellidos e imprime todas las combinaciones posibles de nombres con apellidos.

programa_06.pl

---

# Combinando funciones sobre los arreglos

```{Perl,eval=FALSE}
print "Este programa reeplaza letras dentro de una palabra. 
        Introduce una palabra: ";
chomp(my $palabra = <STDIN>);
print "Escribe la letra a detectar: ";
chomp(my $deteccion = <STDIN>);
print "Con cu치l letra la quieres reemplazar? ";
chomp(my $reemplazo = <STDIN>);

my @arreglo = split("",$palabra);
my @arreglo_reemplazo;

```

---
```{Perl,eval=FALSE}
foreach my $letra (@arreglo) {
	if ($letra eq $deteccion) {
		push(@arreglo_reemplazo,$reemplazo);
	} else {
		push(@arreglo_reemplazo,$letra);
	}
}

my $palabra_modificada = join("",@arreglo_reemplazo);
print "Tu palabra modificada es: $palabra_modificada\n";
```

programa_07.pl

---

# Seleccionando elementos del arreglo con grep

```{Perl,eval=FALSE}
my @numeros = (1,2,3,4,5);

my @numeros_filtrados = grep($_ < 4, @numeros);

print "@numeros_filtrados\n";
```

programa_08.pl

---

```{Perl,eval=FALSE}
my @palabras = ("avion","ave","avioneta","avena");

my @palabras_filtradas = grep(/avion/, @palabras);

print "@palabras_filtradas\n";
```

programa_09.pl

---
# Modificar todos elementos del arreglo con map

```{Perl,eval=FALSE}
my @palabras = ("avion","ave","avioneta","avena");

my @palabras_modificadas=map("La palabra es: $_",@palabras);

print join("\n",@palabras_modificadas), "\n";
```

programa_10.pl

---
# Slicing

Se crea un nuevo arreglo a partir de otro arreglo seleccionando m치s de un elemento.

```{Perl,eval=FALSE}
my @palabras = ("avion", "ave", "avioneta", "avena");

print "@palabras\n";

my @seleccionadas = @palabras[0,1,3];
my @seleccionadas2 = @palabras[0..2];

print "@seleccionadas\n@seleccionadas2\n";
```

programa_11.pl

